// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-27-BjVIKsliqblovYMdj1QwoZcbnX8',
    appId: '1:157487917065:web:f0e3200de2ce12c68bb0d8',
    messagingSenderId: '157487917065',
    projectId: 'tareas-78037',
    authDomain: 'tareas-78037.firebaseapp.com',
    storageBucket: 'tareas-78037.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjIPAGsHs7miEuGzbDL4kavE9GGEvsl4',
    appId: '1:157487917065:android:4b8ad696cbadf1ff8bb0d8',
    messagingSenderId: '157487917065',
    projectId: 'tareas-78037',
    storageBucket: 'tareas-78037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAZej3cTZM3siFZO2-fD-1Eysvv69m_4',
    appId: '1:157487917065:ios:f94540cc9df2b7b58bb0d8',
    messagingSenderId: '157487917065',
    projectId: 'tareas-78037',
    storageBucket: 'tareas-78037.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOAZej3cTZM3siFZO2-fD-1Eysvv69m_4',
    appId: '1:157487917065:ios:e033df7ce5600b1d8bb0d8',
    messagingSenderId: '157487917065',
    projectId: 'tareas-78037',
    storageBucket: 'tareas-78037.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
